name: Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout development files
      uses: actions/checkout@v5
      with:
        sparse-checkout-cone-mode: false
        sparse-checkout: |
          backend/
          compose-deployment.yml
          frontend/

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build docker images
      run: docker compose -f compose-deployment.yml build

    - name: Push images to docker hub
      run: docker compose -f compose-deployment.yml push

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Go to ubuntu directory
        run : cd /home/ubuntu
      
      - name: Checkout deployment files
        uses: actions/checkout@v5
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            backend-configmap.yml
            backend-deployment.yml
            frontend-configmap.yml
            frontend-deployment.yml
      
      - name: Update deployment
        run: kubectl apply -f .
